  profile       = "e2esaprofile"
  ami_name      = "e2esa-aws-ubuntu-golden"
  instance_type = "t2.micro"
  region        = "us-east-1"
  source_ami    = "ami-053b0d53c279acc90"
  ssh_username  = "ubuntu"
  pkr_bucket_name_ubuntu2204_aws ="ubuntu22-nginx-aws"
  pkr_bucket_name_rhel9_aws ="rhel9-nginx-aws"